/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

/**
 * 插入订阅
 */
export function dbInsertSubscription(doc: Subscription) {
    return invoke()<boolean>("db_insert_subscription", { doc })
}

/**
 * 订阅分组
 */
export type Subscription = { id: number; name: string; url: string; disabled: boolean | null }
